# Generated by Django 3.0.3 on 2020-02-11 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flickr_id', models.CharField(max_length=30)),
                ('name', models.CharField(default=None, max_length=255)),
                ('member_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flickr_id', models.CharField(max_length=30)),
                ('owner', models.CharField(default=None, max_length=255, null=True)),
                ('title', models.CharField(default=None, max_length=255, null=True)),
                ('image', models.FileField(upload_to='')),
                ('secret', models.CharField(default=None, max_length=50, null=True)),
                ('farm', models.CharField(default=None, max_length=50, null=True)),
                ('server', models.CharField(default=None, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('comments_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='GroupImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_images', to='apis.Group')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_images', to='apis.Images')),
            ],
            options={
                'db_table': 'group_images',
            },
        ),
    ]
